### PR TITLE
Remove exists since underlying Async.exists was removed

### PR DESCRIPTION
**Pull request by sigma-andex**
**Description of the change**

Update for https://github.com/purescript-node/purescript-node-fs/pull/61

---

**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Review by JordanMartinez — APPROVED** [review]

**Comment by JordanMartinez** [comment]
:ping_pong: @thomashoneyman

**Comment by thomashoneyman** [comment]
I’m not sure we can just replace the asynchronous exists with a liftAff over the synchronous one — @natefaubion, do you have any opinion on that?

Since you can call liftAff on any of these functions that run synchronously in Effect, I don’t think they need to be explicitly ported over to this library. Why not just remove this function altogether?

**Comment by natefaubion** [comment]
I agree with @thomashoneyman. Exporting this as Aff seems like a footgun.

**Comment by sigma-andex** [comment]
Ok I removed it again.

**Comment by JordanMartinez** [comment]
@sigma-andex Sorry about misleading you. I was focusing too much on preventing unneeded breakage rather than the other considerations Thomas brought up.

@thomashoneyman Looks like this PR is ready to be approved now.

**Comment by sigma-andex** [comment]
> @sigma-andex Sorry about misleading you. I was focusing too much on preventing unneeded breakage rather than the other considerations Thomas brought up.

No worries!

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
