### PR TITLE
Updates for 1.0 libraries

### PR DESCRIPTION
**Pull request by paf31**
cc @felixSchl @hdgarrood

### CODE REVIEW

**Comment by hdgarrood** [comment]
:+1: lgtm

**Comment by hdgarrood** [comment]
Ah wait, it looks like we should update .travis.yml to stop testing on unsupported nodes, and also update the version of `pulp` this depends on to fix the CI.

**Comment by paf31** [comment]
Hmm, the build is stalling for some reason. I'm not sure why.

**Comment by paf31** [comment]
Looks like it's building now.

**Comment by garyb** [comment]
Try switching to the `trusty` build, the non-trusty builds hang randomly all the time.

**Comment by paf31** [comment]
This is much faster now, thanks.

**Comment by paf31** [comment]
Should I release this as 1.0 then?

**Comment by hdgarrood** [comment]
No objections here.

**Pull request merged**
