### PR TITLE
Update to purescript 0.7

### PR DESCRIPTION
**Pull request by paf31**
/cc @garyb @felixSchl 

This is a minimal set of changes.

### CODE REVIEW

**Comment by felixSchl** [comment]
I just cannot get this project to build after applying the patch. I take we have to upgrade `gulp-purescript` to it's purescript-0.7 compatible release and update our usage of it (the API has changed under our feet, also refer c45d0bab2c3e649bb120217b08a119f9b25fb387).

I took a quick stab at it but it winged that prelude was defined multiple times now?

**Comment by paf31** [comment]
Did you clear out `bower_components` etc.? Does `psc --version` say `0.7`?

**Comment by felixSchl** [comment]
It says `0.6.8` because I have not `npm install -g`-ed it yet. That brings up an interesting issue though, our refs are not buildable standalone because they rely on some omnipresent version of purescript without specifying the compiler version they require. I wonder if gulp purescript gives us the chance to choose a version to use for the compiler.

**Comment by felixSchl** [comment]
I guess this would also be pending a purescript 0.7 release to npm.

**Comment by felixSchl** [comment]
I filed an issue for this: purescript-contrib/gulp-purescript#50

**Comment by paf31** [comment]
I don't use `gulp` so I'm not certain about how to fix the issues you're seeing, but I know you need to have `psc` 0.7 on your PATH.

**Comment by garyb** [comment]
:+1: for the changes.

**Comment by paf31** [comment]
Can I merge this then? Seems the `gulp` issue is unrelated.

**Comment by felixSchl** [comment]
Personally I would wait until it's in a compilable state before merging into master. I am going to look into this. Just not too sure when, my second daughter just got born hours ago :) either way my vote is to keep this on a branch until ready. @garyb what do u reckon?

**Comment by paf31** [comment]
Congratulations :D

**Comment by garyb** [comment]
Congrats! :tada:

**Comment by felixSchl** [comment]
I've made a couple of changes, including an update to the gulpfile, the way the docs are generated and so on. I made sure to create atomic commits so it's easier to get an overview. We can squash before merge if so desired. It runs fine after `git stash && git clean -fdx && npm install && bower install && gulp example`, but I would appreciate a review if there's something we missed?

**Comment by paf31** [comment]
Looks fine, but I don't use `gulp` so I don't feel strongly :)

**Comment by paf31** [comment]
Can we get this merged then?

**Comment by felixSchl** [comment]
I don't see why not, I will take care of it.

**Pull request merged**
